/* AUTO-GENERATED by scripts/extract-policy.ts
 * Keyword: 여성창업보육센터 | Slug: childcare | Generated: 2026-05-15T05:44:48.431Z
 * Sources: 3/10 | PAA: 0 | Amounts: 0
 *
 * NEXT: npm run verify -- childcare
 */

export const childcarePolicy = {
  "id": "__AUTO_ID__",
  "type": "cash",
  "title": "2026 여성창업보육센터",
  "slug": "childcare",
  "org": "__FILL_ORG__",
  "cat": "지원금",
  "catSlug": "fund",
  "amount": "__amount__",
  "deadline": "__deadline__",
  "views": 0,
  "applyUrl": "https://www.gov.kr/portal/search?query=%EC%97%AC%EC%84%B1%EC%B0%BD%EC%97%85%EB%B3%B4%EC%9C%A1%EC%84%BC%ED%84%B0",
  "datePublished": "2026-05-15T05:44:48.431Z",
  "dateModified": "2026-05-15T05:44:48.431Z",
  "summary": "요청하신 기사는 삭제되었거나 조회가 되지 않는 자료입니다. 입력한 페이지가 정확한지 다시 한번 확인해 주시기 바랍니다. 방문하시려는 페이지의 주소가 잘못 입력되었거나, 페이지의 주소가 변경 혹은 삭제되어 요청하신 페이지를 찾을 수 없습니다. 입력하신 주소가 정확한지 다시 한번 확인해 주시기 바랍니다. 방문하려는 페이지의 주소가 잘못 입력되었거나, 페이지 변경, 삭제 등으로 인하여 요청하신 페이지를 찾을 수 없습니다.",
  "audience": "__audience__",
  "titleKeywords": {
    "k1": "신청 자격",
    "k2": "금액",
    "k3": "신청 방법",
    "compare": "여성창업보육센터 대상"
  },
  "keyFacts": {
    "지원유형": {
      "value": "__지원유형__",
      "source": {
        "url": "https://www.korea.kr/search/search.do?searchKey=ALL&searchKeyword=%EC%97%AC%EC%84%B1%EC%B0%BD%EC%97%85%EB%B3%B4%EC%9C%A1%EC%84%BC%ED%84%B0",
        "text": "",
        "verifiedAt": "2026-05-15"
      }
    },
    "지원금액": {
      "value": "__amount__",
      "source": {
        "url": "https://www.korea.kr/search/search.do?searchKey=ALL&searchKeyword=%EC%97%AC%EC%84%B1%EC%B0%BD%EC%97%85%EB%B3%B4%EC%9C%A1%EC%84%BC%ED%84%B0",
        "text": "",
        "verifiedAt": "2026-05-15"
      }
    },
    "지원대상": {
      "value": "__대상__",
      "source": {
        "url": "https://www.korea.kr/search/search.do?searchKey=ALL&searchKeyword=%EC%97%AC%EC%84%B1%EC%B0%BD%EC%97%85%EB%B3%B4%EC%9C%A1%EC%84%BC%ED%84%B0",
        "text": "",
        "verifiedAt": "2026-05-15"
      }
    },
    "신청방법": {
      "value": "방문하시려는 페이지의 주소가 잘못 입력되었거나, 페이지의 주소가 변경 혹은 삭제되어 요청하신 페이지를 찾을 수 없습니다.",
      "source": {
        "url": "https://www.korea.kr/search/search.do?searchKey=ALL&searchKeyword=%EC%97%AC%EC%84%B1%EC%B0%BD%EC%97%85%EB%B3%B4%EC%9C%A1%EC%84%BC%ED%84%B0",
        "text": "방문하시려는 페이지의 주소가 잘못 입력되었거나, 페이지의 주소가 변경 혹은 삭제되어 요청하신 페이지를 찾을 수 없습니다.",
        "verifiedAt": "2026-05-15"
      }
    },
    "신청기한": {
      "value": "__기한__",
      "source": {
        "url": "https://www.korea.kr/search/search.do?searchKey=ALL&searchKeyword=%EC%97%AC%EC%84%B1%EC%B0%BD%EC%97%85%EB%B3%B4%EC%9C%A1%EC%84%BC%ED%84%B0",
        "text": "",
        "verifiedAt": "2026-05-15"
      }
    },
    "문의처": {
      "value": "__문의처__",
      "source": {
        "url": "https://www.korea.kr/search/search.do?searchKey=ALL&searchKeyword=%EC%97%AC%EC%84%B1%EC%B0%BD%EC%97%85%EB%B3%B4%EC%9C%A1%EC%84%BC%ED%84%B0",
        "text": "",
        "verifiedAt": "2026-05-15"
      }
    },
    "관련법령": {
      "value": "__법령__",
      "source": {
        "url": "",
        "text": "",
        "verifiedAt": "2026-05-15"
      }
    },
    "지급방식": {
      "value": "__지급방식__",
      "source": {
        "url": "https://www.korea.kr/search/search.do?searchKey=ALL&searchKeyword=%EC%97%AC%EC%84%B1%EC%B0%BD%EC%97%85%EB%B3%B4%EC%9C%A1%EC%84%BC%ED%84%B0",
        "text": "",
        "verifiedAt": "2026-05-15"
      }
    },
    "비고": {
      "value": "__비고__",
      "source": {
        "url": "https://www.korea.kr/search/search.do?searchKey=ALL&searchKeyword=%EC%97%AC%EC%84%B1%EC%B0%BD%EC%97%85%EB%B3%B4%EC%9C%A1%EC%84%BC%ED%84%B0",
        "text": "",
        "verifiedAt": "2026-05-15"
      }
    }
  },
  "keyFactsHighlights": {},
  "qa": [
    {
      "q": "여성창업보육센터 금액은 얼마인가요?",
      "anchor": "q-amount",
      "intro": "요청하신 기사는 삭제되었거나 조회가 되지 않는 자료입니다. 입력한 페이지가 정확한지 다시 한번 확인해 주시기 바랍니다. 방문하시려는 페이지의 주소가 잘못 입력되었거나, 페이지의 주소가 변경 혹은 삭제되어 요청하신 페이지를 찾을 수 없습니다. 입력하신 주소가 정확한지 다시 한번 확인해 주시기 바랍니다. 방문하려는 페이지의 주소가 잘못 입력되었거나, 페이지 변경, 삭제 등으로 인하여 요청하신 페이지를 찾을 수 없습니다.",
      "highlights": [
        "여성창업보육센터",
        "방문"
      ],
      "box": {
        "label": "지원금액",
        "content": "__amount__"
      },
      "sourceNote": "* 출처: korea.kr"
    },
    {
      "q": "여성창업보육센터 누가 받을 수 있나요?",
      "anchor": "q-eligibility",
      "intro": "방문하시려는 페이지의 주소가 잘못 입력되었거나, 페이지의 주소가 변경 혹은 삭제되어 요청하신 페이지를 찾을 수 없습니다. 입력하신 주소가 정확한지 다시 한번 확인해 주시기 바랍니다. 방문하려는 페이지의 주소가 잘못 입력되었거나, 페이지 변경, 삭제 등으로 인하여 요청하신 페이지를 찾을 수 없습니다. 입력하신 주소가 정확한지 다시 한 번 확인해 주시기 바랍니다.",
      "highlights": [],
      "box": {
        "label": "지원대상",
        "content": "__대상__"
      },
      "sourceNote": "* 출처: korea.kr"
    },
    {
      "q": "여성창업보육센터 어떻게 신청하나요?",
      "anchor": "q-apply",
      "intro": "방문하려는 페이지의 주소가 잘못 입력되었거나, 페이지 변경, 삭제 등으로 인하여 요청하신 페이지를 찾을 수 없습니다. 입력하신 주소가 정확한지 다시 한 번 확인해 주시기 바랍니다. 여성창업보육센터에 대한 자세한 내용은 정부 공식 자료에서 확인할 수 있습니다.",
      "highlights": [],
      "box": {
        "label": "신청 채널",
        "content": "방문하시려는 페이지의 주소가 잘못 입력되었거나, 페이지의 주소가 변경 혹은 삭제되어 요청하신 페이지를 찾을 수 없습니다.\n방문하려는 페이지의 주소가 잘못 입력되었거나, 페이지 변경, 삭제 등으로 인하여 요청하신 페이지를 찾을 수 없습니다."
      },
      "sourceNote": "* 출처: korea.kr"
    },
    {
      "q": "__질문4__",
      "anchor": "q-extra-3",
      "intro": "여성창업보육센터에 대한 자세한 내용은 정부 공식 자료에서 확인할 수 있습니다.",
      "highlights": [
        "여성창업보육센터",
        "방문"
      ],
      "box": {
        "label": "__라벨__",
        "content": "__내용__"
      },
      "sourceNote": "* 출처: korea.kr"
    },
    {
      "q": "__질문5__",
      "anchor": "q-extra-4",
      "intro": "여성창업보육센터에 대한 자세한 내용은 정부 공식 자료에서 확인할 수 있습니다.",
      "highlights": [
        "여성창업보육센터",
        "방문"
      ],
      "box": {
        "label": "__라벨__",
        "content": "__내용__"
      },
      "sourceNote": "* 출처: korea.kr"
    },
    {
      "q": "__질문6__",
      "anchor": "q-extra-5",
      "intro": "여성창업보육센터에 대한 자세한 내용은 정부 공식 자료에서 확인할 수 있습니다.",
      "highlights": [
        "여성창업보육센터",
        "방문"
      ],
      "box": {
        "label": "__라벨__",
        "content": "__내용__"
      },
      "sourceNote": "* 출처: korea.kr"
    },
    {
      "q": "__질문7__",
      "anchor": "q-extra-6",
      "intro": "여성창업보육센터에 대한 자세한 내용은 정부 공식 자료에서 확인할 수 있습니다.",
      "highlights": [
        "여성창업보육센터",
        "방문"
      ],
      "box": {
        "label": "__라벨__",
        "content": "__내용__"
      },
      "sourceNote": "* 출처: korea.kr"
    }
  ],
  "faq": [],
  "sources": [
    {
      "label": "korea.kr",
      "url": "https://www.korea.kr/search/search.do?searchKey=ALL&searchKeyword=%EC%97%AC%EC%84%B1%EC%B0%BD%EC%97%85%EB%B3%B4%EC%9C%A1%EC%84%BC%ED%84%B0"
    },
    {
      "label": "mohw.go.kr",
      "url": "https://www.mohw.go.kr/search/srcWordSearch.es?searchWord=%EC%97%AC%EC%84%B1%EC%B0%BD%EC%97%85%EB%B3%B4%EC%9C%A1%EC%84%BC%ED%84%B0&mid=a10100000000"
    },
    {
      "label": "gov.kr",
      "url": "https://www.gov.kr/portal/search?query=%EC%97%AC%EC%84%B1%EC%B0%BD%EC%97%85%EB%B3%B4%EC%9C%A1%EC%84%BC%ED%84%B0"
    }
  ]
} as const;

export const childcareSpokes = [
  {
    "slug": "amount",
    "title": "여성창업보육센터 금액, __금액__ __세부__ 차이 | 합산은?",
    "role": "amount",
    "content": ""
  },
  {
    "slug": "eligibility",
    "title": "여성창업보육센터 신청 자격, 누가 받나? | 외국인·보호시설 가능?",
    "role": "eligibility",
    "content": ""
  },
  {
    "slug": "apply",
    "title": "여성창업보육센터 신청 방법, 필요 서류 | 기한 끝내기",
    "role": "apply",
    "content": "방문하시려는 페이지의 주소가 잘못 입력되었거나, 페이지의 주소가 변경 혹은 삭제되어 요청하신 페이지를 찾을 수 없습니다.\n\n방문하려는 페이지의 주소가 잘못 입력되었거나, 페이지 변경, 삭제 등으로 인하여 요청하신 페이지를 찾을 수 없습니다."
  },
  {
    "slug": "usage",
    "title": "여성창업보육센터 사용처, 사용기한, 제외 업종 | 정리",
    "role": "usage",
    "content": ""
  },
  {
    "slug": "overlap",
    "title": "여성창업보육센터 부모급여 아동수당 중복 | 출산축하금까지 다 받기",
    "role": "overlap",
    "content": ""
  }
] as const;
