/* AUTO-GENERATED by scripts/extract-policy.ts
 * Keyword: 해외취업지원 K-Move 스쿨 | Slug: k-move | Generated: 2026-05-15T05:34:33.005Z
 * Sources: 5/10 | PAA: 3 | Amounts: 2
 *
 * NEXT: npm run verify -- k-move
 */

export const kMovePolicy = {
  "id": "__AUTO_ID__",
  "type": "cash",
  "title": "2026 해외취업지원 K-Move 스쿨",
  "slug": "k-move",
  "org": "__FILL_ORG__",
  "cat": "지원금",
  "catSlug": "fund",
  "amount": "1억원",
  "deadline": "__deadline__",
  "views": 0,
  "applyUrl": "https://www.gov.kr/portal/search?query=%ED%95%B4%EC%99%B8%EC%B7%A8%EC%97%85%EC%A7%80%EC%9B%90%20K-Move%20%EC%8A%A4%EC%BF%A8",
  "datePublished": "2026-05-15T05:34:33.004Z",
  "dateModified": "2026-05-15T05:34:33.004Z",
  "summary": "요청하신 기사는 삭제되었거나 조회가 되지 않는 자료입니다. 입력한 페이지가 정확한지 다시 한번 확인해 주시기 바랍니다. 방문하시려는 페이지의 주소가 잘못 입력되었거나, 페이지의 주소가 변경 혹은 삭제되어 요청하신 페이지를 찾을 수 없습니다. 입력하신 주소가 정확한지 다시 한번 확인해 주시기 바랍니다. 방문하려는 페이지의 주소가 잘못 입력되었거나, 페이지 변경, 삭제 등으로 인하여 요청하신 페이지를 찾을 수 없습니다.",
  "audience": "kr›policyitrd K-Move 스쿨 | 고용노동부 > 정책소개 > 정책안내 정책명 : K-Move 스쿨, 대상자 및 분야 : 청년, 이전글 : 1억원 미만 건설공사 무료 기술지원, 다음글 : K-디지털 기초역량훈련 해외취업지원사업 - 고용노동부 ○ 해외 진출을 희망하는 청년을 연수, 알선 취업 및 정착지원, 정보제공 등을 통하여 해외취업으로 연계하는 것이며, 주요 내용으로는 K-Move스쿨, 민간해외취업알선 및 해외취업정착지원금 등이 있습니다.",
  "titleKeywords": {
    "k1": "월드잡플러스",
    "k2": "www.worldjob.or.kr›ovsea",
    "k3": "www.worldjob.or.kr",
    "compare": "ovsea"
  },
  "keyFacts": {
    "지원유형": {
      "value": "__지원유형__",
      "source": {
        "url": "https://www.korea.kr/search/search.do?searchKey=ALL&searchKeyword=%ED%95%B4%EC%99%B8%EC%B7%A8%EC%97%85%EC%A7%80%EC%9B%90%20K-Move%20%EC%8A%A4%EC%BF%A8",
        "text": "",
        "verifiedAt": "2026-05-15"
      }
    },
    "지원금액": {
      "value": "1억원",
      "source": {
        "url": "https://www.korea.kr/search/search.do?searchKey=ALL&searchKeyword=%ED%95%B4%EC%99%B8%EC%B7%A8%EC%97%85%EC%A7%80%EC%9B%90%20K-Move%20%EC%8A%A4%EC%BF%A8",
        "text": "kr›policyitrd K-Move 스쿨 | 고용노동부 > 정책소개 > 정책안내 정책명 : K-Move 스쿨, 대상자 및 분야 : 청년, 이전글 : 1억원 미만 건설공사 무료 기술지원, 다음글 : K-디지털 기초역량훈련 해외취업지원사업 - 고용노동부 ○ 해외 진출을 희망하는 청년을 연수, 알선 취업 및 정착지원, 정보제공 등을 통하여 해외취업으로 연계하는 것이며, 주요 내용으로는 K-Move스쿨, 민간해외취업알선 및 해외취업정착지원금 등이 있습니다.",
        "verifiedAt": "2026-05-15"
      }
    },
    "지원대상": {
      "value": "kr›policyitrd K-Move 스쿨 | 고용노동부 > 정책소개 > 정책안내 정책명 : K-Move 스쿨, 대상자 및 분야 : 청년, 이전",
      "source": {
        "url": "https://www.korea.kr/search/search.do?searchKey=ALL&searchKeyword=%ED%95%B4%EC%99%B8%EC%B7%A8%EC%97%85%EC%A7%80%EC%9B%90%20K-Move%20%EC%8A%A4%EC%BF%A8",
        "text": "kr›policyitrd K-Move 스쿨 | 고용노동부 > 정책소개 > 정책안내 정책명 : K-Move 스쿨, 대상자 및 분야 : 청년, 이전글 : 1억원 미만 건설공사 무료 기술지원, 다음글 : K-디지털 기초역량훈련 해외취업지원사업 - 고용노동부 ○ 해외 진출을 희망하는 청년을 연수, 알선 취업 및 정착지원, 정보제공 등을 통하여 해외취업으로 연계하는 것이며, 주요 내용으로는 K-Move스쿨, 민간해외취업알선 및 해외취업정착지원금 등이 있습니다.",
        "verifiedAt": "2026-05-15"
      }
    },
    "신청방법": {
      "value": "방문하시려는 페이지의 주소가 잘못 입력되었거나, 페이지의 주소가 변경 혹은 삭제되어 요청하신 페이지를 찾을 수 없습니다.",
      "source": {
        "url": "https://www.korea.kr/search/search.do?searchKey=ALL&searchKeyword=%ED%95%B4%EC%99%B8%EC%B7%A8%EC%97%85%EC%A7%80%EC%9B%90%20K-Move%20%EC%8A%A4%EC%BF%A8",
        "text": "방문하시려는 페이지의 주소가 잘못 입력되었거나, 페이지의 주소가 변경 혹은 삭제되어 요청하신 페이지를 찾을 수 없습니다.",
        "verifiedAt": "2026-05-15"
      }
    },
    "신청기한": {
      "value": "__기한__",
      "source": {
        "url": "https://www.korea.kr/search/search.do?searchKey=ALL&searchKeyword=%ED%95%B4%EC%99%B8%EC%B7%A8%EC%97%85%EC%A7%80%EC%9B%90%20K-Move%20%EC%8A%A4%EC%BF%A8",
        "text": "",
        "verifiedAt": "2026-05-15"
      }
    },
    "문의처": {
      "value": "__문의처__",
      "source": {
        "url": "https://www.korea.kr/search/search.do?searchKey=ALL&searchKeyword=%ED%95%B4%EC%99%B8%EC%B7%A8%EC%97%85%EC%A7%80%EC%9B%90%20K-Move%20%EC%8A%A4%EC%BF%A8",
        "text": "",
        "verifiedAt": "2026-05-15"
      }
    },
    "관련법령": {
      "value": "__법령__",
      "source": {
        "url": "",
        "text": "",
        "verifiedAt": "2026-05-15"
      }
    },
    "지급방식": {
      "value": "__지급방식__",
      "source": {
        "url": "https://www.korea.kr/search/search.do?searchKey=ALL&searchKeyword=%ED%95%B4%EC%99%B8%EC%B7%A8%EC%97%85%EC%A7%80%EC%9B%90%20K-Move%20%EC%8A%A4%EC%BF%A8",
        "text": "",
        "verifiedAt": "2026-05-15"
      }
    },
    "비고": {
      "value": "__비고__",
      "source": {
        "url": "https://www.korea.kr/search/search.do?searchKey=ALL&searchKeyword=%ED%95%B4%EC%99%B8%EC%B7%A8%EC%97%85%EC%A7%80%EC%9B%90%20K-Move%20%EC%8A%A4%EC%BF%A8",
        "text": "",
        "verifiedAt": "2026-05-15"
      }
    }
  },
  "keyFactsHighlights": {},
  "qa": [
    {
      "q": "해외취업지원 K-Move 스쿨 금액은 얼마인가요?",
      "anchor": "q-amount",
      "intro": "요청하신 기사는 삭제되었거나 조회가 되지 않는 자료입니다. 입력한 페이지가 정확한지 다시 한번 확인해 주시기 바랍니다. 방문하시려는 페이지의 주소가 잘못 입력되었거나, 페이지의 주소가 변경 혹은 삭제되어 요청하신 페이지를 찾을 수 없습니다. 입력하신 주소가 정확한지 다시 한번 확인해 주시기 바랍니다. 방문하려는 페이지의 주소가 잘못 입력되었거나, 페이지 변경, 삭제 등으로 인하여 요청하신 페이지를 찾을 수 없습니다.",
      "highlights": [
        "해외취업지원 K-Move 스쿨",
        "1억원",
        "100%",
        "온라인"
      ],
      "table": {
        "caption": "지원 금액 정리",
        "headers": [
          "구분",
          "금액",
          "근거"
        ],
        "rows": [
          [
            "항목 1",
            "1억원",
            "kr›policyitrd K-Move 스쿨 | 고용노동부 > 정책소개 > 정책안내 정책명 : K-Move 스쿨, 대상자 및 분야 : 청년, 이전..."
          ],
          [
            "항목 2",
            "100%",
            "해외취업지원(K-Move 스쿨) 지원대상 • 대한민국 국민으로서 해외취업에 결격사유가 없는 34세 이하인 청년 • 구인업체가 요구한 채용조건(연..."
          ]
        ]
      },
      "box": {
        "label": "지원금액",
        "content": "1억원, 100%"
      },
      "sourceNote": "* 출처: korea.kr"
    },
    {
      "q": "해외취업지원 K-Move 스쿨 누가 받을 수 있나요?",
      "anchor": "q-eligibility",
      "intro": "방문하시려는 페이지의 주소가 잘못 입력되었거나, 페이지의 주소가 변경 혹은 삭제되어 요청하신 페이지를 찾을 수 없습니다. 입력하신 주소가 정확한지 다시 한번 확인해 주시기 바랍니다. 방문하려는 페이지의 주소가 잘못 입력되었거나, 페이지 변경, 삭제 등으로 인하여 요청하신 페이지를 찾을 수 없습니다. 입력하신 주소가 정확한지 다시 한 번 확인해 주시기 바랍니다.",
      "highlights": [
        "방문"
      ],
      "table": {
        "caption": "신청 자격 요약",
        "headers": [
          "조건",
          "내용"
        ],
        "rows": [
          [
            "조건 1",
            "kr›policyitrd K-Move 스쿨 | 고용노동부 > 정책소개 > 정책안내 정책명 : K-Move 스쿨, 대상자 및 분야 : 청년, 이전글 : 1억원 미만 건설공사 무료 기..."
          ],
          [
            "조건 2",
            "4 오뎅이의 일상이야기 2주 전 [K-Move 스쿨] 해외취업연수사업 지원 과정 -1 미취업 청년 • 학력: 대학교 졸업자 또는 졸업예정자 (보통 4학년 1학기 이상 수료자) • ..."
          ],
          [
            "조건 3",
            "및 취업을 위한 해외 출입국 및 비자발급이 불가한 자 ▪ 연수개시일 1년 이내 8개월 이상 연수 또는 취업 대상 국가에 해외 체류 사실이 있는 자 - 해외 유학생 대상 모집으로."
          ],
          [
            "조건 4",
            "해외취업지원(K-Move 스쿨) 지원대상 • 대한민국 국민으로서 해외취업에 결격사유가 없는 34세 이하인 청년 • 구인업체가 요구한 채용조건(연령 등)에 부합하는 자 핵심내용 • ..."
          ],
          [
            "조건 5",
            "kr›월드잡플러스-k-move-스쿨-해외취업연수 월드잡플러스 K-Move 스쿨 무료 해외취업연수 지원 대상, 내용, 방법 2023."
          ]
        ]
      },
      "box": {
        "label": "지원대상",
        "content": "kr›policyitrd K-Move 스쿨 | 고용노동부 > 정책소개 > 정책안내 정책명 : K-Move 스쿨, 대상자 및 분야 : 청년, 이전글 : 1억원 미만 건설공사 무료 기술지원, 다음글 : K-디지털 기초역량훈련 해외취업지원사업 - 고용노동부 ○ 해외 진출을 희망하는 청년을 연수, 알선 취업 및 정착지원, 정보제공 등을 통하여 해외취업으로 연계하는 것이며, 주요 내용으로는 K-Move스쿨, 민간해외취업알선 및 해외취업정착지원금 등이 있습니다.\n4 오뎅이의 일상이야기 2주 전 [K-Move 스쿨] 해외취업연수사업 지원 과정 -1 미취업 청년 • 학력: 대학교 졸업자 또는 졸업예정자 (보통 4학년 1학기 이상 수료자) • 기타: 해외 취업 비자 발급에 결격 사유가 없어야 하며, 최근 1년 이내에 다른 정부 지원 해외 연수 과정에 참여한 이력이 없어야 함 (여기서 저는 해외봉사를 갔다 왔는데 K-Move 스쿨을 운영하는 한국산업인력공단은 코이카와 협력 관계에 있기 때문에 오히려 강점!\n및 취업을 위한 해외 출입국 및 비자발급이 불가한 자 ▪ 연수개시일 1년 이내 8개월 이상 연수 또는 취업 대상 국가에 해외 체류 사실이 있는 자 - 해외 유학생 대상 모집으로."
      },
      "sourceNote": "* 출처: korea.kr"
    },
    {
      "q": "해외취업지원 K-Move 스쿨 어떻게 신청하나요?",
      "anchor": "q-apply",
      "intro": "방문하려는 페이지의 주소가 잘못 입력되었거나, 페이지 변경, 삭제 등으로 인하여 요청하신 페이지를 찾을 수 없습니다. 입력하신 주소가 정확한지 다시 한 번 확인해 주시기 바랍니다. 14)2026-05-08 이전 다음 멈춤 정책실현국민여러분의 참여가 이렇게 바꾸었습니다. 생각실현 2026년 행복청 민원행정 제도개선을 위한 국민의견수렴 [빛나라 빛나, 대나무!",
      "highlights": [],
      "box": {
        "label": "신청 채널",
        "content": "방문하시려는 페이지의 주소가 잘못 입력되었거나, 페이지의 주소가 변경 혹은 삭제되어 요청하신 페이지를 찾을 수 없습니다.\n방문하려는 페이지의 주소가 잘못 입력되었거나, 페이지 변경, 삭제 등으로 인하여 요청하신 페이지를 찾을 수 없습니다.\ncom/ 시사IT아카데미 K-MOVE 정부지원 취업과정 해외취업 연수과정 KMOVE 일본 취업 과정, 도쿄 오사카 기업 취업처 연계와 연수 교육 제공 이벤트 시사일본어학원 강사진 직강 일본IT취업 국비지원교육 온라인상담 헥사곤지엠아이 hexagongmi."
      },
      "sourceNote": "* 출처: korea.kr"
    },
    {
      "q": "알림을 모두 삭제하시겠습니까?",
      "anchor": "q-paa-1",
      "intro": "14)2026-05-08 이전 다음 멈춤 정책실현국민여러분의 참여가 이렇게 바꾸었습니다. 생각실현 2026년 행복청 민원행정 제도개선을 위한 국민의견수렴 [빛나라 빛나, 대나무! 국민권익위원회 이 누리집은 국민권익위원회에서 운영하는 누리집입니다. com/ 시사IT아카데미 K-MOVE 정부지원 취업과정 해외취업 연수과정 KMOVE 일본 취업 과정, 도쿄 오사카 기업 취업처 연계와 연수 교육 제공 이벤트 시사일본어학원 강사진 직강 일본IT취업 국비지원교육 온라인상담 헥사곤지엠아이 hexagongmi.",
      "highlights": [],
      "box": {
        "label": "관련 답변",
        "content": "__답변__"
      },
      "sourceNote": "* 출처: korea.kr"
    },
    {
      "q": "좋아하는 건 누구나 남기고 싶으니까 클립 올리면 매주 쌓이는 Npay 포인트",
      "anchor": "q-paa-2",
      "intro": "국민권익위원회 이 누리집은 국민권익위원회에서 운영하는 누리집입니다. com/ 시사IT아카데미 K-MOVE 정부지원 취업과정 해외취업 연수과정 KMOVE 일본 취업 과정, 도쿄 오사카 기업 취업처 연계와 연수 교육 제공 이벤트 시사일본어학원 강사진 직강 일본IT취업 국비지원교육 온라인상담 헥사곤지엠아이 hexagongmi. com 헥사곤 일본/베트남 해외취업 전액무료, 연수생 모집중!",
      "highlights": [],
      "box": {
        "label": "관련 답변",
        "content": "__답변__"
      },
      "sourceNote": "* 출처: korea.kr"
    },
    {
      "q": "좋아하는 건 누구나 남기고 싶으니까",
      "anchor": "q-paa-3",
      "intro": "com 헥사곤 일본/베트남 해외취업 전액무료, 연수생 모집중! 최우수 국비 연수기관 전액무료, 26년 일본,베트남취업 연수생 모집중! 국비과정안내 온라인상담 취업 후기 다음으로 이동 일본취업 공항취업 지상직 IT취업 채용사이트 한국능력개발 khrd. org 해외취업연수 우수기관 한능전 베트남 한국산업인력공단 해위취업연수 우수기관 더보기 월드잡플러스 www.",
      "highlights": [],
      "box": {
        "label": "관련 답변",
        "content": "__답변__"
      },
      "sourceNote": "* 출처: korea.kr"
    },
    {
      "q": "__질문7__",
      "anchor": "q-extra-6",
      "intro": "국비과정안내 온라인상담 취업 후기 다음으로 이동 일본취업 공항취업 지상직 IT취업 채용사이트 한국능력개발 khrd. org 해외취업연수 우수기관 한능전 베트남 한국산업인력공단 해위취업연수 우수기관 더보기 월드잡플러스 www. kr›policyitrd K-Move 스쿨 | 고용노동부 > 정책소개 > 정책안내 정책명 : K-Move 스쿨, 대상자 및 분야 : 청년, 이전글 : 1억원 미만 건설공사 무료 기술지원, 다음글 : K-디지털 기초역량훈련 해외취업지원사업 - 고용노동부 ○ 해외 진출을 희망하는 청년을 연수, 알선 취업 및 정착지원, 정보제공 등을 통하여 해외취업으로 연계하는 것이며, 주요 내용으로는 K-Move스쿨, 민간해외취업알선 및 해외취업정착지원금 등이 있습니다.",
      "highlights": [
        "해외취업지원 K-Move 스쿨",
        "1억원"
      ],
      "box": {
        "label": "__라벨__",
        "content": "__내용__"
      },
      "sourceNote": "* 출처: korea.kr"
    }
  ],
  "faq": [
    {
      "q": "알림을 모두 삭제하시겠습니까?",
      "a": "자세한 내용은 해외취업지원 K-Move 스쿨 공식 안내를 확인하세요.",
      "source": "korea.kr",
      "sourceUrl": "https://www.korea.kr/search/search.do?searchKey=ALL&searchKeyword=%ED%95%B4%EC%99%B8%EC%B7%A8%EC%97%85%EC%A7%80%EC%9B%90%20K-Move%20%EC%8A%A4%EC%BF%A8"
    },
    {
      "q": "좋아하는 건 누구나 남기고 싶으니까 클립 올리면 매주 쌓이는 Npay 포인트",
      "a": "자세한 내용은 해외취업지원 K-Move 스쿨 공식 안내를 확인하세요.",
      "source": "korea.kr",
      "sourceUrl": "https://www.korea.kr/search/search.do?searchKey=ALL&searchKeyword=%ED%95%B4%EC%99%B8%EC%B7%A8%EC%97%85%EC%A7%80%EC%9B%90%20K-Move%20%EC%8A%A4%EC%BF%A8"
    },
    {
      "q": "좋아하는 건 누구나 남기고 싶으니까",
      "a": "자세한 내용은 해외취업지원 K-Move 스쿨 공식 안내를 확인하세요.",
      "source": "korea.kr",
      "sourceUrl": "https://www.korea.kr/search/search.do?searchKey=ALL&searchKeyword=%ED%95%B4%EC%99%B8%EC%B7%A8%EC%97%85%EC%A7%80%EC%9B%90%20K-Move%20%EC%8A%A4%EC%BF%A8"
    }
  ],
  "sources": [
    {
      "label": "korea.kr",
      "url": "https://www.korea.kr/search/search.do?searchKey=ALL&searchKeyword=%ED%95%B4%EC%99%B8%EC%B7%A8%EC%97%85%EC%A7%80%EC%9B%90%20K-Move%20%EC%8A%A4%EC%BF%A8"
    },
    {
      "label": "mohw.go.kr",
      "url": "https://www.mohw.go.kr/search/srcWordSearch.es?searchWord=%ED%95%B4%EC%99%B8%EC%B7%A8%EC%97%85%EC%A7%80%EC%9B%90%20K-Move%20%EC%8A%A4%EC%BF%A8&mid=a10100000000"
    },
    {
      "label": "gov.kr",
      "url": "https://www.gov.kr/portal/search?query=%ED%95%B4%EC%99%B8%EC%B7%A8%EC%97%85%EC%A7%80%EC%9B%90%20K-Move%20%EC%8A%A4%EC%BF%A8"
    },
    {
      "label": "epeople.go.kr",
      "url": "https://www.epeople.go.kr/jsp/user/UserMain.paid?keyword=%ED%95%B4%EC%99%B8%EC%B7%A8%EC%97%85%EC%A7%80%EC%9B%90%20K-Move%20%EC%8A%A4%EC%BF%A8"
    },
    {
      "label": "naver",
      "url": "https://search.naver.com/search.naver?query=%ED%95%B4%EC%99%B8%EC%B7%A8%EC%97%85%EC%A7%80%EC%9B%90%20K-Move%20%EC%8A%A4%EC%BF%A8"
    }
  ]
} as const;

export const kMoveSpokes = [
  {
    "slug": "amount",
    "title": "해외취업지원 K-Move 스쿨 금액, 1억원 100% 차이 | 합산은?",
    "role": "amount",
    "content": "- 1억원 : kr›policyitrd K-Move 스쿨 | 고용노동부 > 정책소개 > 정책안내 정책명 : K-Move 스쿨, 대상자 및 분야 : 청년, 이전글 : 1억원 미만 건설공사 무료 기\n- 100% : 해외취업지원(K-Move 스쿨) 지원대상 • 대한민국 국민으로서 해외취업에 결격사유가 없는 34세 이하인 청년 • 구인업체가 요구한 채용조건(연령 등)에 부합하는 자 핵심내용 • "
  },
  {
    "slug": "eligibility",
    "title": "해외취업지원 K-Move 스쿨 신청 자격, 누가 받나? | 외국인·보호시설 가능?",
    "role": "eligibility",
    "content": "kr›policyitrd K-Move 스쿨 | 고용노동부 > 정책소개 > 정책안내 정책명 : K-Move 스쿨, 대상자 및 분야 : 청년, 이전글 : 1억원 미만 건설공사 무료 기술지원, 다음글 : K-디지털 기초역량훈련 해외취업지원사업 - 고용노동부 ○ 해외 진출을 희망하는 청년을 연수, 알선 취업 및 정착지원, 정보제공 등을 통하여 해외취업으로 연계하는 것이며, 주요 내용으로는 K-Move스쿨, 민간해외취업알선 및 해외취업정착지원금 등이 있습니다.\n\n4 오뎅이의 일상이야기 2주 전 [K-Move 스쿨] 해외취업연수사업 지원 과정 -1 미취업 청년 • 학력: 대학교 졸업자 또는 졸업예정자 (보통 4학년 1학기 이상 수료자) • 기타: 해외 취업 비자 발급에 결격 사유가 없어야 하며, 최근 1년 이내에 다른 정부 지원 해외 연수 과정에 참여한 이력이 없어야 함 (여기서 저는 해외봉사를 갔다 왔는데 K-Move 스쿨을 운영하는 한국산업인력공단은 코이카와 협력 관계에 있기 때문에 오히려 강점!\n\n및 취업을 위한 해외 출입국 및 비자발급이 불가한 자 ▪ 연수개시일 1년 이내 8개월 이상 연수 또는 취업 대상 국가에 해외 체류 사실이 있는 자 - 해외 유학생 대상 모집으로.\n\n해외취업지원(K-Move 스쿨) 지원대상 • 대한민국 국민으로서 해외취업에 결격사유가 없는 34세 이하인 청년 • 구인업체가 요구한 채용조건(연령 등)에 부합하는 자 핵심내용 • 해외취업에 필요한 기업맞춤형 연수교육(연수비의 80~100% 지원) 해외취업지원(K-Move 스쿨) • 어학과정, 직무, 현장실습(OJT) 및 기타 교육(취업상담, 기업 에티켓 교육, 해당.\n\nkr›월드잡플러스-k-move-스쿨-해외취업연수 월드잡플러스 K-Move 스쿨 무료 해외취업연수 지원 대상, 내용, 방법 2023."
  },
  {
    "slug": "apply",
    "title": "해외취업지원 K-Move 스쿨 신청 방법, 필요 서류 | 기한 끝내기",
    "role": "apply",
    "content": "방문하시려는 페이지의 주소가 잘못 입력되었거나, 페이지의 주소가 변경 혹은 삭제되어 요청하신 페이지를 찾을 수 없습니다.\n\n방문하려는 페이지의 주소가 잘못 입력되었거나, 페이지 변경, 삭제 등으로 인하여 요청하신 페이지를 찾을 수 없습니다.\n\ncom/ 시사IT아카데미 K-MOVE 정부지원 취업과정 해외취업 연수과정 KMOVE 일본 취업 과정, 도쿄 오사카 기업 취업처 연계와 연수 교육 제공 이벤트 시사일본어학원 강사진 직강 일본IT취업 국비지원교육 온라인상담 헥사곤지엠아이 hexagongmi.\n\n국비과정안내 온라인상담 취업 후기 다음으로 이동 일본취업 공항취업 지상직 IT취업 채용사이트 한국능력개발 khrd.\n\n그래서 오늘은 한국산업인력공단에서 안내하는 해외취업지원(K-Move 스쿨) 내용을 바탕으로, 실제로 어떤 지원을 받을 수 있고 어떻게 신청하면 되는지 한 번에 정리해볼게요."
  },
  {
    "slug": "usage",
    "title": "해외취업지원 K-Move 스쿨 사용처, 사용기한, 제외 업종 | 정리",
    "role": "usage",
    "content": ""
  },
  {
    "slug": "overlap",
    "title": "해외취업지원 K-Move 스쿨 부모급여 아동수당 중복 | 출산축하금까지 다 받기",
    "role": "overlap",
    "content": "세계와 인재를 연결하는 청년 해외취업지원사업_나를 더 세계롭게 K-Move 스쿨, 해외일경험지원사업, 해외취업 정착지원금, 국내 재취업지원서비스 등 해외진출 전 단계를 한 번에 이용할 수 있는 통합플랫폼 월드잡플러스🌍 해외진출의 시작부터 국내 재취업까지 청년들의 끊임없는 도전을 위해 앞으로도 월드잡플러스가 함께하겠습니다!\n\nkr›global K-Move 스쿨 | 해외취업 | 경기과학기술대학교 국제교류원 청년실업문제를 해외취업으로 해결하려는 정부의 의지가 반영된 사업의 일환으로 제시된 “K-Move 스쿨”에 본교가 선정되어, 많은 졸업예정자 학생들이 학교에서 별도의 수업을 수강하고,졸업과 동시에 해외에서 취업할 수 있는 기회를 갖게 되었습니다.\n\n어학능력, 면접, 학점 등의 심사를 통해서 최종 선발된 “K-Move 스쿨” 합격자는 마지막 졸업학기 동안에 학과의 교과과정대신에 본교가 준비하고 정부가 승인한 “어학 전공” 과목을 수강함으로써, 학점인정과 함께 해외취업에 도전할 수 있는 기회를 갖게 됩니다."
  }
] as const;
