/* AUTO-GENERATED by scripts/extract-policy.ts
 * Keyword: 한국형 온라인 공개강좌 K-MOOC | Slug: k-mooc | Generated: 2026-05-15T05:31:47.630Z
 * Sources: 5/10 | PAA: 4 | Amounts: 0
 *
 * NEXT: npm run verify -- k-mooc
 */

export const kMoocPolicy = {
  "id": "__AUTO_ID__",
  "type": "cash",
  "title": "2026 한국형 온라인 공개강좌 K-MOOC",
  "slug": "k-mooc",
  "org": "__FILL_ORG__",
  "cat": "지원금",
  "catSlug": "fund",
  "amount": "__amount__",
  "deadline": "__deadline__",
  "views": 0,
  "applyUrl": "https://www.gov.kr/portal/search?query=%ED%95%9C%EA%B5%AD%ED%98%95%20%EC%98%A8%EB%9D%BC%EC%9D%B8%20%EA%B3%B5%EA%B0%9C%EA%B0%95%EC%A2%8C%20K-MOOC",
  "datePublished": "2026-05-15T05:31:47.630Z",
  "dateModified": "2026-05-15T05:31:47.630Z",
  "summary": "요청하신 기사는 삭제되었거나 조회가 되지 않는 자료입니다. 입력한 페이지가 정확한지 다시 한번 확인해 주시기 바랍니다. 방문하시려는 페이지의 주소가 잘못 입력되었거나, 페이지의 주소가 변경 혹은 삭제되어 요청하신 페이지를 찾을 수 없습니다. 입력하신 주소가 정확한지 다시 한번 확인해 주시기 바랍니다. 방문하려는 페이지의 주소가 잘못 입력되었거나, 페이지 변경, 삭제 등으로 인하여 요청하신 페이지를 찾을 수 없습니다.",
  "audience": "특화강좌 등 110개 강좌 선정 - 다양한 신규 과정, 올 9월부터 선보일 예정 교육부(부총리 겸 교육부장관 이주호)와 국가평생교육진흥원(원장 강대중)은 ‘2023년 한국형 온라인 공개강좌(이하 ‘케이무크(K-MOOC)’) 선정 결과’를 발표한다.",
  "titleKeywords": {
    "k1": "교육부",
    "k2": "www.moe.go.kr›boardCnts",
    "k3": "www.moe.go.kr",
    "compare": "boardCnts"
  },
  "keyFacts": {
    "지원유형": {
      "value": "__지원유형__",
      "source": {
        "url": "https://www.korea.kr/search/search.do?searchKey=ALL&searchKeyword=%ED%95%9C%EA%B5%AD%ED%98%95%20%EC%98%A8%EB%9D%BC%EC%9D%B8%20%EA%B3%B5%EA%B0%9C%EA%B0%95%EC%A2%8C%20K-MOOC",
        "text": "",
        "verifiedAt": "2026-05-15"
      }
    },
    "지원금액": {
      "value": "__amount__",
      "source": {
        "url": "https://www.korea.kr/search/search.do?searchKey=ALL&searchKeyword=%ED%95%9C%EA%B5%AD%ED%98%95%20%EC%98%A8%EB%9D%BC%EC%9D%B8%20%EA%B3%B5%EA%B0%9C%EA%B0%95%EC%A2%8C%20K-MOOC",
        "text": "",
        "verifiedAt": "2026-05-15"
      }
    },
    "지원대상": {
      "value": "특화강좌 등 110개 강좌 선정 - 다양한 신규 과정, 올 9월부터 선보일 예정 교육부(부총리 겸 교육부장관 이주호)와 국가평생교육진흥원(원장 ",
      "source": {
        "url": "https://www.korea.kr/search/search.do?searchKey=ALL&searchKeyword=%ED%95%9C%EA%B5%AD%ED%98%95%20%EC%98%A8%EB%9D%BC%EC%9D%B8%20%EA%B3%B5%EA%B0%9C%EA%B0%95%EC%A2%8C%20K-MOOC",
        "text": "특화강좌 등 110개 강좌 선정 - 다양한 신규 과정, 올 9월부터 선보일 예정 교육부(부총리 겸 교육부장관 이주호)와 국가평생교육진흥원(원장 강대중)은 ‘2023년 한국형 온라인 공개강좌(이하 ‘케이무크(K-MOOC)’) 선정 결과’를 발표한다.",
        "verifiedAt": "2026-05-15"
      }
    },
    "신청방법": {
      "value": "방문하시려는 페이지의 주소가 잘못 입력되었거나, 페이지의 주소가 변경 혹은 삭제되어 요청하신 페이지를 찾을 수 없습니다.",
      "source": {
        "url": "https://www.korea.kr/search/search.do?searchKey=ALL&searchKeyword=%ED%95%9C%EA%B5%AD%ED%98%95%20%EC%98%A8%EB%9D%BC%EC%9D%B8%20%EA%B3%B5%EA%B0%9C%EA%B0%95%EC%A2%8C%20K-MOOC",
        "text": "방문하시려는 페이지의 주소가 잘못 입력되었거나, 페이지의 주소가 변경 혹은 삭제되어 요청하신 페이지를 찾을 수 없습니다.",
        "verifiedAt": "2026-05-15"
      }
    },
    "신청기한": {
      "value": "__기한__",
      "source": {
        "url": "https://www.korea.kr/search/search.do?searchKey=ALL&searchKeyword=%ED%95%9C%EA%B5%AD%ED%98%95%20%EC%98%A8%EB%9D%BC%EC%9D%B8%20%EA%B3%B5%EA%B0%9C%EA%B0%95%EC%A2%8C%20K-MOOC",
        "text": "",
        "verifiedAt": "2026-05-15"
      }
    },
    "문의처": {
      "value": "__문의처__",
      "source": {
        "url": "https://www.korea.kr/search/search.do?searchKey=ALL&searchKeyword=%ED%95%9C%EA%B5%AD%ED%98%95%20%EC%98%A8%EB%9D%BC%EC%9D%B8%20%EA%B3%B5%EA%B0%9C%EA%B0%95%EC%A2%8C%20K-MOOC",
        "text": "",
        "verifiedAt": "2026-05-15"
      }
    },
    "관련법령": {
      "value": "__법령__",
      "source": {
        "url": "",
        "text": "",
        "verifiedAt": "2026-05-15"
      }
    },
    "지급방식": {
      "value": "__지급방식__",
      "source": {
        "url": "https://www.korea.kr/search/search.do?searchKey=ALL&searchKeyword=%ED%95%9C%EA%B5%AD%ED%98%95%20%EC%98%A8%EB%9D%BC%EC%9D%B8%20%EA%B3%B5%EA%B0%9C%EA%B0%95%EC%A2%8C%20K-MOOC",
        "text": "",
        "verifiedAt": "2026-05-15"
      }
    },
    "비고": {
      "value": "__비고__",
      "source": {
        "url": "https://www.korea.kr/search/search.do?searchKey=ALL&searchKeyword=%ED%95%9C%EA%B5%AD%ED%98%95%20%EC%98%A8%EB%9D%BC%EC%9D%B8%20%EA%B3%B5%EA%B0%9C%EA%B0%95%EC%A2%8C%20K-MOOC",
        "text": "",
        "verifiedAt": "2026-05-15"
      }
    }
  },
  "keyFactsHighlights": {},
  "qa": [
    {
      "q": "한국형 온라인 공개강좌 K-MOOC 금액은 얼마인가요?",
      "anchor": "q-amount",
      "intro": "요청하신 기사는 삭제되었거나 조회가 되지 않는 자료입니다. 입력한 페이지가 정확한지 다시 한번 확인해 주시기 바랍니다. 방문하시려는 페이지의 주소가 잘못 입력되었거나, 페이지의 주소가 변경 혹은 삭제되어 요청하신 페이지를 찾을 수 없습니다. 입력하신 주소가 정확한지 다시 한번 확인해 주시기 바랍니다. 방문하려는 페이지의 주소가 잘못 입력되었거나, 페이지 변경, 삭제 등으로 인하여 요청하신 페이지를 찾을 수 없습니다.",
      "highlights": [
        "한국형 온라인 공개강좌 K-MOOC",
        "온라인",
        "방문"
      ],
      "box": {
        "label": "지원금액",
        "content": "__amount__"
      },
      "sourceNote": "* 출처: korea.kr"
    },
    {
      "q": "한국형 온라인 공개강좌 K-MOOC 누가 받을 수 있나요?",
      "anchor": "q-eligibility",
      "intro": "방문하시려는 페이지의 주소가 잘못 입력되었거나, 페이지의 주소가 변경 혹은 삭제되어 요청하신 페이지를 찾을 수 없습니다. 입력하신 주소가 정확한지 다시 한번 확인해 주시기 바랍니다. 방문하려는 페이지의 주소가 잘못 입력되었거나, 페이지 변경, 삭제 등으로 인하여 요청하신 페이지를 찾을 수 없습니다. 입력하신 주소가 정확한지 다시 한 번 확인해 주시기 바랍니다.",
      "highlights": [],
      "table": {
        "caption": "신청 자격 요약",
        "headers": [
          "조건",
          "내용"
        ],
        "rows": [
          [
            "조건 1",
            "특화강좌 등 110개 강좌 선정 - 다양한 신규 과정, 올 9월부터 선보일 예정 교육부(부총리 겸 교육부장관 이주호)와 국가평생교육진흥원(원장 강대중)은 ‘2023년 한국형 온라인..."
          ],
          [
            "조건 2",
            "2024년 12월 31일 기준으로 175개 이상의 대학들이 참여하고, 5318개가."
          ]
        ]
      },
      "box": {
        "label": "지원대상",
        "content": "특화강좌 등 110개 강좌 선정 - 다양한 신규 과정, 올 9월부터 선보일 예정 교육부(부총리 겸 교육부장관 이주호)와 국가평생교육진흥원(원장 강대중)은 ‘2023년 한국형 온라인 공개강좌(이하 ‘케이무크(K-MOOC)’) 선정 결과’를 발표한다.\n2024년 12월 31일 기준으로 175개 이상의 대학들이 참여하고, 5318개가."
      },
      "sourceNote": "* 출처: korea.kr"
    },
    {
      "q": "한국형 온라인 공개강좌 K-MOOC 어떻게 신청하나요?",
      "anchor": "q-apply",
      "intro": "방문하려는 페이지의 주소가 잘못 입력되었거나, 페이지 변경, 삭제 등으로 인하여 요청하신 페이지를 찾을 수 없습니다. 입력하신 주소가 정확한지 다시 한 번 확인해 주시기 바랍니다. 14)2026-05-08 이전 다음 멈춤 정책실현국민여러분의 참여가 이렇게 바꾸었습니다. 생각실현 2026년 행복청 민원행정 제도개선을 위한 국민의견수렴 [빛나라 빛나, 대나무!",
      "highlights": [],
      "box": {
        "label": "신청 채널",
        "content": "방문하시려는 페이지의 주소가 잘못 입력되었거나, 페이지의 주소가 변경 혹은 삭제되어 요청하신 페이지를 찾을 수 없습니다.\n방문하려는 페이지의 주소가 잘못 입력되었거나, 페이지 변경, 삭제 등으로 인하여 요청하신 페이지를 찾을 수 없습니다.\n특화강좌 등 110개 강좌 선정 - 다양한 신규 과정, 올 9월부터 선보일 예정 교육부(부총리 겸 교육부장관 이주호)와 국가평생교육진흥원(원장 강대중)은 ‘2023년 한국형 온라인 공개강좌(이하 ‘케이무크(K-MOOC)’) 선정 결과’를 발표한다."
      },
      "sourceNote": "* 출처: korea.kr"
    },
    {
      "q": "알림을 모두 삭제하시겠습니까?",
      "anchor": "q-paa-1",
      "intro": "14)2026-05-08 이전 다음 멈춤 정책실현국민여러분의 참여가 이렇게 바꾸었습니다. 생각실현 2026년 행복청 민원행정 제도개선을 위한 국민의견수렴 [빛나라 빛나, 대나무! 국민권익위원회 이 누리집은 국민권익위원회에서 운영하는 누리집입니다. 특화강좌 등 110개 강좌 선정 - 다양한 신규 과정, 올 9월부터 선보일 예정 교육부(부총리 겸 교육부장관 이주호)와 국가평생교육진흥원(원장 강대중)은 ‘2023년 한국형 온라인 공개강좌(이하 ‘케이무크(K-MOOC)’) 선정 결과’를 발표한다.",
      "highlights": [],
      "box": {
        "label": "관련 답변",
        "content": "__답변__"
      },
      "sourceNote": "* 출처: korea.kr"
    },
    {
      "q": "누구나, 어디서나! 무료로 만나는 대학 수준 온라인 강의  K-MOOC",
      "anchor": "q-paa-2",
      "intro": "국민권익위원회 이 누리집은 국민권익위원회에서 운영하는 누리집입니다. 특화강좌 등 110개 강좌 선정 - 다양한 신규 과정, 올 9월부터 선보일 예정 교육부(부총리 겸 교육부장관 이주호)와 국가평생교육진흥원(원장 강대중)은 ‘2023년 한국형 온라인 공개강좌(이하 ‘케이무크(K-MOOC)’) 선정 결과’를 발표한다. kr K-MOOC 학점은행제 강좌 인문 학점은행제 소개 커뮤니티 상시강좌 매치업 한국형 온라인 공개강좌 K-MOOC 안내.",
      "highlights": [],
      "box": {
        "label": "관련 답변",
        "content": "__답변__"
      },
      "sourceNote": "* 출처: korea.kr"
    },
    {
      "q": "좋아하는 건 누구나 남기고 싶으니까 클립 올리면 매주 쌓이는 Npay 포인트",
      "anchor": "q-paa-3",
      "intro": "kr K-MOOC 학점은행제 강좌 인문 학점은행제 소개 커뮤니티 상시강좌 매치업 한국형 온라인 공개강좌 K-MOOC 안내. K-MOOC 소개 K-MOOC의 의미와 비전 ; 무크(MOOC)란 Massive, Open, Online, Course의 줄임말로 오픈형 온라인 학습 과정을 뜻합니다. 알려주려는 자와 배우려는 자를 쉽고 한층 가깝게 연결함으로써 많은 사람들이 어제보다 나은 미래, 새로운 미래, 더 다채로운 미래를 만들 수 있도록 도울 것입니다.",
      "highlights": [],
      "box": {
        "label": "관련 답변",
        "content": "__답변__"
      },
      "sourceNote": "* 출처: korea.kr"
    },
    {
      "q": "좋아하는 건 누구나 남기고 싶으니까",
      "anchor": "q-paa-4",
      "intro": "알려주려는 자와 배우려는 자를 쉽고 한층 가깝게 연결함으로써 많은 사람들이 어제보다 나은 미래, 새로운 미래, 더 다채로운 미래를 만들 수 있도록 도울 것입니다. 2026년 한국형 온라인 공개강좌(K-MOOC) 사업 운영 계획 안내 2026년 한국형 온라인 공개강좌(K-MOOC) 사업 운영 계획 안내입니다. 상세한 내용은 사업 기본계획 및 공고문을 참고하여 주시기 바랍니다.",
      "highlights": [],
      "box": {
        "label": "관련 답변",
        "content": "__답변__"
      },
      "sourceNote": "* 출처: korea.kr"
    }
  ],
  "faq": [
    {
      "q": "알림을 모두 삭제하시겠습니까?",
      "a": "자세한 내용은 한국형 온라인 공개강좌 K-MOOC 공식 안내를 확인하세요.",
      "source": "korea.kr",
      "sourceUrl": "https://www.korea.kr/search/search.do?searchKey=ALL&searchKeyword=%ED%95%9C%EA%B5%AD%ED%98%95%20%EC%98%A8%EB%9D%BC%EC%9D%B8%20%EA%B3%B5%EA%B0%9C%EA%B0%95%EC%A2%8C%20K-MOOC"
    },
    {
      "q": "누구나, 어디서나! 무료로 만나는 대학 수준 온라인 강의  K-MOOC",
      "a": "자세한 내용은 한국형 온라인 공개강좌 K-MOOC 공식 안내를 확인하세요.",
      "source": "korea.kr",
      "sourceUrl": "https://www.korea.kr/search/search.do?searchKey=ALL&searchKeyword=%ED%95%9C%EA%B5%AD%ED%98%95%20%EC%98%A8%EB%9D%BC%EC%9D%B8%20%EA%B3%B5%EA%B0%9C%EA%B0%95%EC%A2%8C%20K-MOOC"
    },
    {
      "q": "좋아하는 건 누구나 남기고 싶으니까 클립 올리면 매주 쌓이는 Npay 포인트",
      "a": "자세한 내용은 한국형 온라인 공개강좌 K-MOOC 공식 안내를 확인하세요.",
      "source": "korea.kr",
      "sourceUrl": "https://www.korea.kr/search/search.do?searchKey=ALL&searchKeyword=%ED%95%9C%EA%B5%AD%ED%98%95%20%EC%98%A8%EB%9D%BC%EC%9D%B8%20%EA%B3%B5%EA%B0%9C%EA%B0%95%EC%A2%8C%20K-MOOC"
    },
    {
      "q": "좋아하는 건 누구나 남기고 싶으니까",
      "a": "자세한 내용은 한국형 온라인 공개강좌 K-MOOC 공식 안내를 확인하세요.",
      "source": "korea.kr",
      "sourceUrl": "https://www.korea.kr/search/search.do?searchKey=ALL&searchKeyword=%ED%95%9C%EA%B5%AD%ED%98%95%20%EC%98%A8%EB%9D%BC%EC%9D%B8%20%EA%B3%B5%EA%B0%9C%EA%B0%95%EC%A2%8C%20K-MOOC"
    }
  ],
  "sources": [
    {
      "label": "korea.kr",
      "url": "https://www.korea.kr/search/search.do?searchKey=ALL&searchKeyword=%ED%95%9C%EA%B5%AD%ED%98%95%20%EC%98%A8%EB%9D%BC%EC%9D%B8%20%EA%B3%B5%EA%B0%9C%EA%B0%95%EC%A2%8C%20K-MOOC"
    },
    {
      "label": "mohw.go.kr",
      "url": "https://www.mohw.go.kr/search/srcWordSearch.es?searchWord=%ED%95%9C%EA%B5%AD%ED%98%95%20%EC%98%A8%EB%9D%BC%EC%9D%B8%20%EA%B3%B5%EA%B0%9C%EA%B0%95%EC%A2%8C%20K-MOOC&mid=a10100000000"
    },
    {
      "label": "gov.kr",
      "url": "https://www.gov.kr/portal/search?query=%ED%95%9C%EA%B5%AD%ED%98%95%20%EC%98%A8%EB%9D%BC%EC%9D%B8%20%EA%B3%B5%EA%B0%9C%EA%B0%95%EC%A2%8C%20K-MOOC"
    },
    {
      "label": "epeople.go.kr",
      "url": "https://www.epeople.go.kr/jsp/user/UserMain.paid?keyword=%ED%95%9C%EA%B5%AD%ED%98%95%20%EC%98%A8%EB%9D%BC%EC%9D%B8%20%EA%B3%B5%EA%B0%9C%EA%B0%95%EC%A2%8C%20K-MOOC"
    },
    {
      "label": "naver",
      "url": "https://search.naver.com/search.naver?query=%ED%95%9C%EA%B5%AD%ED%98%95%20%EC%98%A8%EB%9D%BC%EC%9D%B8%20%EA%B3%B5%EA%B0%9C%EA%B0%95%EC%A2%8C%20K-MOOC"
    }
  ]
} as const;

export const kMoocSpokes = [
  {
    "slug": "amount",
    "title": "한국형 온라인 공개강좌 K-MOOC 금액, __금액__ __세부__ 차이 | 합산은?",
    "role": "amount",
    "content": ""
  },
  {
    "slug": "eligibility",
    "title": "한국형 온라인 공개강좌 K-MOOC 신청 자격, 누가 받나? | 외국인·보호시설 가능?",
    "role": "eligibility",
    "content": "특화강좌 등 110개 강좌 선정 - 다양한 신규 과정, 올 9월부터 선보일 예정 교육부(부총리 겸 교육부장관 이주호)와 국가평생교육진흥원(원장 강대중)은 ‘2023년 한국형 온라인 공개강좌(이하 ‘케이무크(K-MOOC)’) 선정 결과’를 발표한다.\n\n2024년 12월 31일 기준으로 175개 이상의 대학들이 참여하고, 5318개가."
  },
  {
    "slug": "apply",
    "title": "한국형 온라인 공개강좌 K-MOOC 신청 방법, 필요 서류 | 기한 끝내기",
    "role": "apply",
    "content": "방문하시려는 페이지의 주소가 잘못 입력되었거나, 페이지의 주소가 변경 혹은 삭제되어 요청하신 페이지를 찾을 수 없습니다.\n\n방문하려는 페이지의 주소가 잘못 입력되었거나, 페이지 변경, 삭제 등으로 인하여 요청하신 페이지를 찾을 수 없습니다.\n\n특화강좌 등 110개 강좌 선정 - 다양한 신규 과정, 올 9월부터 선보일 예정 교육부(부총리 겸 교육부장관 이주호)와 국가평생교육진흥원(원장 강대중)은 ‘2023년 한국형 온라인 공개강좌(이하 ‘케이무크(K-MOOC)’) 선정 결과’를 발표한다.\n\nkr K-MOOC 학점은행제 강좌 인문 학점은행제 소개 커뮤니티 상시강좌 매치업 한국형 온라인 공개강좌 K-MOOC 안내.\n\nK-MOOC 소개 K-MOOC의 의미와 비전 ; 무크(MOOC)란 Massive, Open, Online, Course의 줄임말로 오픈형 온라인 학습 과정을 뜻합니다."
  },
  {
    "slug": "usage",
    "title": "한국형 온라인 공개강좌 K-MOOC 사용처, 사용기한, 제외 업종 | 정리",
    "role": "usage",
    "content": ""
  },
  {
    "slug": "overlap",
    "title": "한국형 온라인 공개강좌 K-MOOC 부모급여 아동수당 중복 | 출산축하금까지 다 받기",
    "role": "overlap",
    "content": ""
  }
] as const;
