/* AUTO-GENERATED by scripts/extract-policy.ts
 * Keyword: 농촌출신대학생 학자금 대출 | Slug: loan | Generated: 2026-05-15T05:35:25.806Z
 * Sources: 5/10 | PAA: 6 | Amounts: 1
 *
 * NEXT: npm run verify -- loan
 */

export const loanPolicy = {
  "id": "__AUTO_ID__",
  "type": "cash",
  "title": "2026 농촌출신대학생 학자금 대출",
  "slug": "loan",
  "org": "__FILL_ORG__",
  "cat": "지원금",
  "catSlug": "fund",
  "amount": "3000만원",
  "deadline": "__deadline__",
  "views": 0,
  "applyUrl": "https://www.gov.kr/portal/search?query=%EB%86%8D%EC%B4%8C%EC%B6%9C%EC%8B%A0%EB%8C%80%ED%95%99%EC%83%9D%20%ED%95%99%EC%9E%90%EA%B8%88%20%EB%8C%80%EC%B6%9C",
  "datePublished": "2026-05-15T05:35:25.805Z",
  "dateModified": "2026-05-15T05:35:25.805Z",
  "summary": "요청하신 기사는 삭제되었거나 조회가 되지 않는 자료입니다. 입력한 페이지가 정확한지 다시 한번 확인해 주시기 바랍니다. 방문하시려는 페이지의 주소가 잘못 입력되었거나, 페이지의 주소가 변경 혹은 삭제되어 요청하신 페이지를 찾을 수 없습니다. 입력하신 주소가 정확한지 다시 한번 확인해 주시기 바랍니다. 방문하려는 페이지의 주소가 잘못 입력되었거나, 페이지 변경, 삭제 등으로 인하여 요청하신 페이지를 찾을 수 없습니다.",
  "audience": "지원자격에 해당하시는 학우분들께서는 공지사항을 참고해 주시기 바랍니다.",
  "titleKeywords": {
    "k1": "한국장학재단",
    "k2": "www.kosaf.go.kr›tuition",
    "k3": "www.kosaf.go.kr",
    "compare": "tuition"
  },
  "keyFacts": {
    "지원유형": {
      "value": "__지원유형__",
      "source": {
        "url": "https://www.korea.kr/search/search.do?searchKey=ALL&searchKeyword=%EB%86%8D%EC%B4%8C%EC%B6%9C%EC%8B%A0%EB%8C%80%ED%95%99%EC%83%9D%20%ED%95%99%EC%9E%90%EA%B8%88%20%EB%8C%80%EC%B6%9C",
        "text": "",
        "verifiedAt": "2026-05-15"
      }
    },
    "지원금액": {
      "value": "3000만원",
      "source": {
        "url": "https://www.korea.kr/search/search.do?searchKey=ALL&searchKeyword=%EB%86%8D%EC%B4%8C%EC%B6%9C%EC%8B%A0%EB%8C%80%ED%95%99%EC%83%9D%20%ED%95%99%EC%9E%90%EA%B8%88%20%EB%8C%80%EC%B6%9C",
        "text": "com 당일대출OK, 대출나라 3000만원까지 추가대출OK 타사 대출이 있어도OK 나에게 딱 맞는 대출업체 찾기, 신용/직업 상관없이 당일대출OK, 무서류 즉시송금 더보기 한국장학재단 www.",
        "verifiedAt": "2026-05-15"
      }
    },
    "지원대상": {
      "value": "지원자격에 해당하시는 학우분들께서는 공지사항을 참고해 주시기 바랍니다.",
      "source": {
        "url": "https://www.korea.kr/search/search.do?searchKey=ALL&searchKeyword=%EB%86%8D%EC%B4%8C%EC%B6%9C%EC%8B%A0%EB%8C%80%ED%95%99%EC%83%9D%20%ED%95%99%EC%9E%90%EA%B8%88%20%EB%8C%80%EC%B6%9C",
        "text": "지원자격에 해당하시는 학우분들께서는 공지사항을 참고해 주시기 바랍니다.",
        "verifiedAt": "2026-05-15"
      }
    },
    "신청방법": {
      "value": "방문하시려는 페이지의 주소가 잘못 입력되었거나, 페이지의 주소가 변경 혹은 삭제되어 요청하신 페이지를 찾을 수 없습니다.",
      "source": {
        "url": "https://www.korea.kr/search/search.do?searchKey=ALL&searchKeyword=%EB%86%8D%EC%B4%8C%EC%B6%9C%EC%8B%A0%EB%8C%80%ED%95%99%EC%83%9D%20%ED%95%99%EC%9E%90%EA%B8%88%20%EB%8C%80%EC%B6%9C",
        "text": "방문하시려는 페이지의 주소가 잘못 입력되었거나, 페이지의 주소가 변경 혹은 삭제되어 요청하신 페이지를 찾을 수 없습니다.",
        "verifiedAt": "2026-05-15"
      }
    },
    "신청기한": {
      "value": "__기한__",
      "source": {
        "url": "https://www.korea.kr/search/search.do?searchKey=ALL&searchKeyword=%EB%86%8D%EC%B4%8C%EC%B6%9C%EC%8B%A0%EB%8C%80%ED%95%99%EC%83%9D%20%ED%95%99%EC%9E%90%EA%B8%88%20%EB%8C%80%EC%B6%9C",
        "text": "",
        "verifiedAt": "2026-05-15"
      }
    },
    "문의처": {
      "value": "__문의처__",
      "source": {
        "url": "https://www.korea.kr/search/search.do?searchKey=ALL&searchKeyword=%EB%86%8D%EC%B4%8C%EC%B6%9C%EC%8B%A0%EB%8C%80%ED%95%99%EC%83%9D%20%ED%95%99%EC%9E%90%EA%B8%88%20%EB%8C%80%EC%B6%9C",
        "text": "",
        "verifiedAt": "2026-05-15"
      }
    },
    "관련법령": {
      "value": "__법령__",
      "source": {
        "url": "",
        "text": "",
        "verifiedAt": "2026-05-15"
      }
    },
    "지급방식": {
      "value": "__지급방식__",
      "source": {
        "url": "https://www.korea.kr/search/search.do?searchKey=ALL&searchKeyword=%EB%86%8D%EC%B4%8C%EC%B6%9C%EC%8B%A0%EB%8C%80%ED%95%99%EC%83%9D%20%ED%95%99%EC%9E%90%EA%B8%88%20%EB%8C%80%EC%B6%9C",
        "text": "",
        "verifiedAt": "2026-05-15"
      }
    },
    "비고": {
      "value": "__비고__",
      "source": {
        "url": "https://www.korea.kr/search/search.do?searchKey=ALL&searchKeyword=%EB%86%8D%EC%B4%8C%EC%B6%9C%EC%8B%A0%EB%8C%80%ED%95%99%EC%83%9D%20%ED%95%99%EC%9E%90%EA%B8%88%20%EB%8C%80%EC%B6%9C",
        "text": "",
        "verifiedAt": "2026-05-15"
      }
    }
  },
  "keyFactsHighlights": {},
  "qa": [
    {
      "q": "농촌출신대학생 학자금 대출 금액은 얼마인가요?",
      "anchor": "q-amount",
      "intro": "요청하신 기사는 삭제되었거나 조회가 되지 않는 자료입니다. 입력한 페이지가 정확한지 다시 한번 확인해 주시기 바랍니다. 방문하시려는 페이지의 주소가 잘못 입력되었거나, 페이지의 주소가 변경 혹은 삭제되어 요청하신 페이지를 찾을 수 없습니다. 입력하신 주소가 정확한지 다시 한번 확인해 주시기 바랍니다. 방문하려는 페이지의 주소가 잘못 입력되었거나, 페이지 변경, 삭제 등으로 인하여 요청하신 페이지를 찾을 수 없습니다.",
      "highlights": [
        "농촌출신대학생 학자금 대출",
        "3000만원",
        "복지로",
        "정부24"
      ],
      "box": {
        "label": "지원금액",
        "content": "3000만원"
      },
      "sourceNote": "* 출처: korea.kr"
    },
    {
      "q": "농촌출신대학생 학자금 대출 누가 받을 수 있나요?",
      "anchor": "q-eligibility",
      "intro": "방문하시려는 페이지의 주소가 잘못 입력되었거나, 페이지의 주소가 변경 혹은 삭제되어 요청하신 페이지를 찾을 수 없습니다. 입력하신 주소가 정확한지 다시 한번 확인해 주시기 바랍니다. 방문하려는 페이지의 주소가 잘못 입력되었거나, 페이지 변경, 삭제 등으로 인하여 요청하신 페이지를 찾을 수 없습니다. 입력하신 주소가 정확한지 다시 한 번 확인해 주시기 바랍니다.",
      "highlights": [
        "온라인",
        "방문"
      ],
      "table": {
        "caption": "신청 자격 요약",
        "headers": [
          "조건",
          "내용"
        ],
        "rows": [
          [
            "조건 1",
            "지원자격에 해당하시는 학우분들께서는 공지사항을 참고해 주시기 바랍니다."
          ],
          [
            "조건 2",
            "지원자격 - 농어촌지역에 주민등록 주소를 두고 6개월 이상 거주하거나 농어업에 종사하고 있는."
          ],
          [
            "조건 3",
            "kr) 기초수급자 「국민기초생활 보장법」에 따른 수급자 증명서(생계/의료/보장) 장애인 「장애인복지법」에 따른 장애인 증명서 또는 장애인 등록증(본인 명의, 매학기 제출) 다자녀(..."
          ],
          [
            "조건 4",
            "농촌출신대학생 학자금융자 신청방법 신청 대상은 농어촌 지역에 주민등록상 6개월 이상 거주하며 국내 대학에 재학 중인 학부생으로, 소득 구간에 따른 제한이 있을 수 있으므로 자세한 ..."
          ],
          [
            "조건 5",
            "지원 자격, 신청 조건, 꼭 확인해야 할 사항들을 정리했어요."
          ]
        ]
      },
      "box": {
        "label": "지원대상",
        "content": "지원자격에 해당하시는 학우분들께서는 공지사항을 참고해 주시기 바랍니다.\n지원자격 - 농어촌지역에 주민등록 주소를 두고 6개월 이상 거주하거나 농어업에 종사하고 있는.\nkr) 기초수급자 「국민기초생활 보장법」에 따른 수급자 증명서(생계/의료/보장) 장애인 「장애인복지법」에 따른 장애인 증명서 또는 장애인 등록증(본인 명의, 매학기 제출) 다자녀(3자녀 이상*) *신청자 본인이 다자녀가구 해당 시 (미혼) 생계를 같이하는 부 또는 모 명의 가족관계증명서 (기혼) 본인 명의 가족관계증명서 차상위계층 한부모가족 증명서 ."
      },
      "sourceNote": "* 출처: korea.kr"
    },
    {
      "q": "농촌출신대학생 학자금 대출 어떻게 신청하나요?",
      "anchor": "q-apply",
      "intro": "방문하려는 페이지의 주소가 잘못 입력되었거나, 페이지 변경, 삭제 등으로 인하여 요청하신 페이지를 찾을 수 없습니다. 입력하신 주소가 정확한지 다시 한 번 확인해 주시기 바랍니다. 14)2026-05-08 이전 다음 멈춤 정책실현국민여러분의 참여가 이렇게 바꾸었습니다. 생각실현 2026년 행복청 민원행정 제도개선을 위한 국민의견수렴 [빛나라 빛나, 대나무!",
      "highlights": [],
      "box": {
        "label": "신청 채널",
        "content": "방문하시려는 페이지의 주소가 잘못 입력되었거나, 페이지의 주소가 변경 혹은 삭제되어 요청하신 페이지를 찾을 수 없습니다.\n방문하려는 페이지의 주소가 잘못 입력되었거나, 페이지 변경, 삭제 등으로 인하여 요청하신 페이지를 찾을 수 없습니다.\n; 농어촌출신 학부생에게 등록금 전액을 무이자로 대출해주고 졸업 후 2년 뒤부터 분할상환이 가능하도록 함으로써 농어업인 자녀들의 고등교육기회를 보장하는 대출제도 졸업 후 2년 거치 후, 한 학기 분을 1년 이내 분할 상환 (월별 균등 상환) ※ 상환관련 상세 안내는 학자금대출 상환안내에서 확인 바람 관련문서 더보기 복지로 www."
      },
      "sourceNote": "* 출처: korea.kr"
    },
    {
      "q": "알림을 모두 삭제하시겠습니까?",
      "anchor": "q-paa-1",
      "intro": "14)2026-05-08 이전 다음 멈춤 정책실현국민여러분의 참여가 이렇게 바꾸었습니다. 생각실현 2026년 행복청 민원행정 제도개선을 위한 국민의견수렴 [빛나라 빛나, 대나무! 국민권익위원회 이 누리집은 국민권익위원회에서 운영하는 누리집입니다. com 당일대출OK, 대출나라 3000만원까지 추가대출OK 타사 대출이 있어도OK 나에게 딱 맞는 대출업체 찾기, 신용/직업 상관없이 당일대출OK, 무서류 즉시송금 더보기 한국장학재단 www.",
      "highlights": [],
      "box": {
        "label": "관련 답변",
        "content": "__답변__"
      },
      "sourceNote": "* 출처: korea.kr"
    },
    {
      "q": "장학재단 대출 두종류 대출 동시신청 하신분 계실까요?",
      "anchor": "q-paa-2",
      "intro": "국민권익위원회 이 누리집은 국민권익위원회에서 운영하는 누리집입니다. com 당일대출OK, 대출나라 3000만원까지 추가대출OK 타사 대출이 있어도OK 나에게 딱 맞는 대출업체 찾기, 신용/직업 상관없이 당일대출OK, 무서류 즉시송금 더보기 한국장학재단 www. ; 농어촌출신 학부생에게 등록금 전액을 무이자로 대출해주고 졸업 후 2년 뒤부터 분할상환이 가능하도록 함으로써 농어업인 자녀들의 고등교육기회를 보장하는 대출제도 졸업 후 2년 거치 후, 한 학기 분을 1년 이내 분할 상환 (월별 균등 상환) ※ 상환관련 상세 안내는 학자금대출 상환안내에서 확인 바람 관련문서 더보기 복지로 www.",
      "highlights": [],
      "box": {
        "label": "관련 답변",
        "content": "com 당일대출OK, 대출나라 3000만원까지 추가대출OK 타사 대출이 있어도OK 나에게 딱 맞는 대출업체 찾기, 신용/직업 상관없이 당일대출OK, 무서류 즉시송금 더보기 한국장학재단 www."
      },
      "sourceNote": "* 출처: korea.kr"
    },
    {
      "q": "RE생활비대출은 신입생은 미리 신청이 안되죠?",
      "anchor": "q-paa-3",
      "intro": "; 농어촌출신 학부생에게 등록금 전액을 무이자로 대출해주고 졸업 후 2년 뒤부터 분할상환이 가능하도록 함으로써 농어업인 자녀들의 고등교육기회를 보장하는 대출제도 졸업 후 2년 거치 후, 한 학기 분을 1년 이내 분할 상환 (월별 균등 상환) ※ 상환관련 상세 안내는 학자금대출 상환안내에서 확인 바람 관련문서 더보기 복지로 www. kr›from-rural-area 농촌출신대학생학자금대출 | 영남대학교 장학안내 2024.",
      "highlights": [],
      "box": {
        "label": "관련 답변",
        "content": "__답변__"
      },
      "sourceNote": "* 출처: korea.kr"
    },
    {
      "q": "생활비대출은 신입생은 미리 신청이 안되죠?",
      "anchor": "q-paa-4",
      "intro": "kr ) · 한국장학재단 콜센터 1599-2000 공공데이터포털 www. kr›fileData 한국장학재단_농촌출신대학(원)생 학자금대출 핵심설명서_20260105 2026. 한국장학재단의 학자금대출 제도는 일반 상환 학자금대출, 취업 후 상환 학자금대출, 농촌출신대학(원)생 학자금대출, 학점은행제 학습자 학자금대출 등이 있으며, 이 중 농촌출신대학(원)생 학자금대출 제도는 농어촌출신 학부생 및 대학원생에게 등록금 전액을 무이자로 대출해주고 거치기간과 상환기간을 선택하여 상환이 가능하도록 함으로써 농어업인 자녀들의 고등교육.",
      "highlights": [],
      "box": {
        "label": "관련 답변",
        "content": "__답변__"
      },
      "sourceNote": "* 출처: korea.kr"
    }
  ],
  "faq": [
    {
      "q": "알림을 모두 삭제하시겠습니까?",
      "a": "자세한 내용은 농촌출신대학생 학자금 대출 공식 안내를 확인하세요.",
      "source": "korea.kr",
      "sourceUrl": "https://www.korea.kr/search/search.do?searchKey=ALL&searchKeyword=%EB%86%8D%EC%B4%8C%EC%B6%9C%EC%8B%A0%EB%8C%80%ED%95%99%EC%83%9D%20%ED%95%99%EC%9E%90%EA%B8%88%20%EB%8C%80%EC%B6%9C"
    },
    {
      "q": "장학재단 대출 두종류 대출 동시신청 하신분 계실까요?",
      "a": "com 당일대출OK, 대출나라 3000만원까지 추가대출OK 타사 대출이 있어도OK 나에게 딱 맞는 대출업체 찾기, 신용/직업 상관없이 당일대출OK, 무서류 즉시송금 더보기 한국장학재단 www.",
      "source": "korea.kr",
      "sourceUrl": "https://www.korea.kr/search/search.do?searchKey=ALL&searchKeyword=%EB%86%8D%EC%B4%8C%EC%B6%9C%EC%8B%A0%EB%8C%80%ED%95%99%EC%83%9D%20%ED%95%99%EC%9E%90%EA%B8%88%20%EB%8C%80%EC%B6%9C"
    },
    {
      "q": "RE생활비대출은 신입생은 미리 신청이 안되죠?",
      "a": "자세한 내용은 농촌출신대학생 학자금 대출 공식 안내를 확인하세요.",
      "source": "korea.kr",
      "sourceUrl": "https://www.korea.kr/search/search.do?searchKey=ALL&searchKeyword=%EB%86%8D%EC%B4%8C%EC%B6%9C%EC%8B%A0%EB%8C%80%ED%95%99%EC%83%9D%20%ED%95%99%EC%9E%90%EA%B8%88%20%EB%8C%80%EC%B6%9C"
    },
    {
      "q": "생활비대출은 신입생은 미리 신청이 안되죠?",
      "a": "자세한 내용은 농촌출신대학생 학자금 대출 공식 안내를 확인하세요.",
      "source": "korea.kr",
      "sourceUrl": "https://www.korea.kr/search/search.do?searchKey=ALL&searchKeyword=%EB%86%8D%EC%B4%8C%EC%B6%9C%EC%8B%A0%EB%8C%80%ED%95%99%EC%83%9D%20%ED%95%99%EC%9E%90%EA%B8%88%20%EB%8C%80%EC%B6%9C"
    },
    {
      "q": "좋아하는 건 누구나 남기고 싶으니까 클립 올리면 매주 쌓이는 Npay 포인트",
      "a": "자세한 내용은 농촌출신대학생 학자금 대출 공식 안내를 확인하세요.",
      "source": "korea.kr",
      "sourceUrl": "https://www.korea.kr/search/search.do?searchKey=ALL&searchKeyword=%EB%86%8D%EC%B4%8C%EC%B6%9C%EC%8B%A0%EB%8C%80%ED%95%99%EC%83%9D%20%ED%95%99%EC%9E%90%EA%B8%88%20%EB%8C%80%EC%B6%9C"
    }
  ],
  "sources": [
    {
      "label": "korea.kr",
      "url": "https://www.korea.kr/search/search.do?searchKey=ALL&searchKeyword=%EB%86%8D%EC%B4%8C%EC%B6%9C%EC%8B%A0%EB%8C%80%ED%95%99%EC%83%9D%20%ED%95%99%EC%9E%90%EA%B8%88%20%EB%8C%80%EC%B6%9C"
    },
    {
      "label": "mohw.go.kr",
      "url": "https://www.mohw.go.kr/search/srcWordSearch.es?searchWord=%EB%86%8D%EC%B4%8C%EC%B6%9C%EC%8B%A0%EB%8C%80%ED%95%99%EC%83%9D%20%ED%95%99%EC%9E%90%EA%B8%88%20%EB%8C%80%EC%B6%9C&mid=a10100000000"
    },
    {
      "label": "gov.kr",
      "url": "https://www.gov.kr/portal/search?query=%EB%86%8D%EC%B4%8C%EC%B6%9C%EC%8B%A0%EB%8C%80%ED%95%99%EC%83%9D%20%ED%95%99%EC%9E%90%EA%B8%88%20%EB%8C%80%EC%B6%9C"
    },
    {
      "label": "epeople.go.kr",
      "url": "https://www.epeople.go.kr/jsp/user/UserMain.paid?keyword=%EB%86%8D%EC%B4%8C%EC%B6%9C%EC%8B%A0%EB%8C%80%ED%95%99%EC%83%9D%20%ED%95%99%EC%9E%90%EA%B8%88%20%EB%8C%80%EC%B6%9C"
    },
    {
      "label": "naver",
      "url": "https://search.naver.com/search.naver?query=%EB%86%8D%EC%B4%8C%EC%B6%9C%EC%8B%A0%EB%8C%80%ED%95%99%EC%83%9D%20%ED%95%99%EC%9E%90%EA%B8%88%20%EB%8C%80%EC%B6%9C"
    }
  ]
} as const;

export const loanSpokes = [
  {
    "slug": "amount",
    "title": "농촌출신대학생 학자금 대출 금액, 3000만원 __세부__ 차이 | 합산은?",
    "role": "amount",
    "content": "- 3000만원 : com 당일대출OK, 대출나라 3000만원까지 추가대출OK 타사 대출이 있어도OK 나에게 딱 맞는 대출업체 찾기, 신용/직업 상관없이 당일대출OK, 무서류 즉시송금 더보기 한국장학"
  },
  {
    "slug": "eligibility",
    "title": "농촌출신대학생 학자금 대출 신청 자격, 누가 받나? | 외국인·보호시설 가능?",
    "role": "eligibility",
    "content": "지원자격에 해당하시는 학우분들께서는 공지사항을 참고해 주시기 바랍니다.\n\n지원자격 - 농어촌지역에 주민등록 주소를 두고 6개월 이상 거주하거나 농어업에 종사하고 있는.\n\nkr) 기초수급자 「국민기초생활 보장법」에 따른 수급자 증명서(생계/의료/보장) 장애인 「장애인복지법」에 따른 장애인 증명서 또는 장애인 등록증(본인 명의, 매학기 제출) 다자녀(3자녀 이상*) *신청자 본인이 다자녀가구 해당 시 (미혼) 생계를 같이하는 부 또는 모 명의 가족관계증명서 (기혼) 본인 명의 가족관계증명서 차상위계층 한부모가족 증명서 .\n\n농촌출신대학생 학자금융자 신청방법 신청 대상은 농어촌 지역에 주민등록상 6개월 이상 거주하며 국내 대학에 재학 중인 학부생으로, 소득 구간에 따른 제한이 있을 수 있으므로 자세한 사항은 한국장학재단 누리집을.\n\n지원 자격, 신청 조건, 꼭 확인해야 할 사항들을 정리했어요."
  },
  {
    "slug": "apply",
    "title": "농촌출신대학생 학자금 대출 신청 방법, 필요 서류 | 기한 끝내기",
    "role": "apply",
    "content": "방문하시려는 페이지의 주소가 잘못 입력되었거나, 페이지의 주소가 변경 혹은 삭제되어 요청하신 페이지를 찾을 수 없습니다.\n\n방문하려는 페이지의 주소가 잘못 입력되었거나, 페이지 변경, 삭제 등으로 인하여 요청하신 페이지를 찾을 수 없습니다.\n\n; 농어촌출신 학부생에게 등록금 전액을 무이자로 대출해주고 졸업 후 2년 뒤부터 분할상환이 가능하도록 함으로써 농어업인 자녀들의 고등교육기회를 보장하는 대출제도 졸업 후 2년 거치 후, 한 학기 분을 1년 이내 분할 상환 (월별 균등 상환) ※ 상환관련 상세 안내는 학자금대출 상환안내에서 확인 바람 관련문서 더보기 복지로 www.\n\n정도에 한국장학재단에서 농촌학자금대출을 신청했는데 아직도 심사중으로 뜨는데 왜 이러는지 알 수 있을까요 ㅠ 다음주 월요일에 당장 대학원 등록금을 납부 해야하는데 근 한달간 심사중으로 계속 뜹니다… 안녕하세요 한국장학재단입니다.\n\n■ 2026년 1학기 농촌출신대학(원)생 학자금대출 일정 • 신청 - (1차) 2026."
  },
  {
    "slug": "usage",
    "title": "농촌출신대학생 학자금 대출 사용처, 사용기한, 제외 업종 | 정리",
    "role": "usage",
    "content": "면제 대출 내용 등록금 전액 무이자 대출 대상 등록금: 입학금 + 수업료 생활비 대출은 제외 이자 전액 면제, 상환 부담 없음."
  },
  {
    "slug": "overlap",
    "title": "농촌출신대학생 학자금 대출 부모급여 아동수당 중복 | 출산축하금까지 다 받기",
    "role": "overlap",
    "content": "일반 상환 학자금대출이랑 농촌출신대학생 학자금대출 동시에 신청될까요?\n\n둘다 조건에 맞긴하네요 RE등록금 명목이기 때문에 두개동시에는 안될겁니다."
  }
] as const;
