/* Auto-generated by extract-policy.ts from data/raw/policy-1778794443602.json
 * Generated at: 2026-05-14T21:34:08.010Z
 * Keyword: 고유가 지원금
 *
 * NEXT STEPS (human or AI agent):
 * 1. Fill all __FILL_*__ placeholders with verbatim quotes from data/raw/policy-1778794443602.json
 * 2. Each qa[i].intro must be >=200 chars (Q2 requirement)
 * 3. Each qa[i] must include table or box (Q3)
 * 4. Total tables >=2 (Q4), boxes >=3 (Q5), highlights >=15 (Q6)
 * 5. Run: npm run verify -- policy-1778794443602
 * 6. If FAIL: address each Q1-Q13 failure
 * 7. Run: npm run verify-policy -- policy-1778794443602
 * 8. If PASS: human review then push
 */

export const policy1778794443602Policy = {
  "id": "AUTO_ID",
  "type": "cash",
  "title": "2026 고유가 지원금",
  "slug": "policy-1778794443602",
  "org": "FILL_ORG",
  "cat": "지원금",
  "catSlug": "fund",
  "amount": "FILL_AMOUNT",
  "deadline": "FILL_DEADLINE",
  "views": 0,
  "applyUrl": "https://www.gov.kr",
  "datePublished": "2026-05-14T21:34:08.009Z",
  "dateModified": "2026-05-14T21:34:08.010Z",
  "summary": "__FILL_SUMMARY__ (2-3문장, 정부 자료에서 인용)",
  "audience": "FILL_AUDIENCE",
  "titleKeywords": {
    "k1": "신청 자격",
    "k2": "금액",
    "k3": "사용처",
    "compare": "비교정책"
  },
  "keyFacts": {
    "필드1": "VALUE",
    "필드2": "VALUE",
    "필드3": "VALUE",
    "필드4": "VALUE",
    "필드5": "VALUE",
    "필드6": "VALUE",
    "필드7": "VALUE",
    "필드8": "VALUE",
    "필드9": "VALUE"
  },
  "keyFactsHighlights": {},
  "qa": [],
  "faq": [],
  "sources": []
} as const;

export const policy1778794443602Spokes = [];
