/**
 * scripts/extract-policy.ts
 * Read raw collection JSON -> emit data/policies/<slug>.ts skeleton.
 * Usage: npx tsx scripts/extract-policy.ts <slug>
 *
 * The skeleton is structured for the existing generic renderer.
 * Once raw text is filled, the human (or an AI agent) fills the placeholders
 * with verbatim quotes from the collected sources. No speculation.
 */

import * as fs from 'fs';
import * as path from 'path';

const ROOT = process.cwd();
const RAW_DIR = path.join(ROOT, 'data', 'raw');
const KW_DIR = path.join(ROOT, 'data', 'keywords');
const POLICIES_DIR = path.join(ROOT, 'data', 'policies');

interface SourceHit {
  source: string;
  url: string;
  title?: string;
  text: string;
  fetchedAt: string;
}

interface NaverKeywords {
  paa: string[];
  related: string[];
  autocomplete: string[];
}

interface RawCollection {
  keyword: string;
  slug: string;
  collectedAt: string;
  sources: SourceHit[];
  naver: NaverKeywords;
}

function camelCase(slug: string): string {
  return slug.replace(/[-_](\w)/g, (_, c) => c.toUpperCase());
}

function emitPolicy(raw: RawCollection): string {
  const kw = raw.keyword;
  const slug = raw.slug;
  const varName = camelCase(slug);
  const sourcesFilled = raw.sources.filter((s) => s.text && s.text.length > 0);

  // Pull PAA into FAQ questions verbatim
  const paa = raw.naver.paa.slice(0, 5);

  const policy = {
    id: '__AUTO_ID__',
    type: 'cash',
    title: '2026 ' + kw,
    slug,
    org: '__FILL_ORG__',
    cat: '지원금',
    catSlug: 'fund',
    amount: '__FILL_AMOUNT__',
    deadline: '__FILL_DEADLINE__',
    views: 0,
    applyUrl: 'https://www.gov.kr',
    datePublished: new Date().toISOString(),
    dateModified: new Date().toISOString(),
    summary: '__FILL_SUMMARY__ (2-3문장, 정부 자료에서 인용)',
    audience: '__FILL_AUDIENCE__',

    titleKeywords: {
      k1: raw.naver.related[0] || '신청 자격',
      k2: raw.naver.related[1] || '금액',
      k3: raw.naver.related[2] || '사용처',
      compare: raw.naver.related[3] || '__비교정책__',
    },

    keyFacts: Object.fromEntries(
      Array.from({ length: 9 }, (_, i) => ['__필드' + (i + 1) + '__', '__VALUE__'])
    ),
    keyFactsHighlights: {},

    qa: paa.map((q, i) => ({
      q: q || '__질문' + (i + 1) + '__',
      anchor: 'q-' + (i + 1),
      intro: '__본문 200자 이상 (수집된 source.text에서 1:1 인용)__',
      highlights: [],
      box: { label: '__라벨__', content: '__내용__' },
      sourceNote: '* 출처: ' + (sourcesFilled[0]?.source || 'TBD'),
    })),

    faq: paa.map((q) => ({
      q: q,
      a: '__1-2줄 답변 (source.text 인용)__',
      source: sourcesFilled[0]?.source || 'TBD',
      sourceUrl: sourcesFilled[0]?.url || '',
    })),

    sources: sourcesFilled.map((s) => ({
      label: s.title || s.source,
      url: s.url,
    })),
  };

  const banner = `/* Auto-generated by extract-policy.ts from data/raw/${slug}.json
 * Generated at: ${new Date().toISOString()}
 * Keyword: ${kw}
 *
 * NEXT STEPS (human or AI agent):
 * 1. Fill all __FILL_*__ placeholders with verbatim quotes from data/raw/${slug}.json
 * 2. Each qa[i].intro must be >=200 chars (Q2 requirement)
 * 3. Each qa[i] must include table or box (Q3)
 * 4. Total tables >=2 (Q4), boxes >=3 (Q5), highlights >=15 (Q6)
 * 5. Run: npm run verify -- ${slug}
 * 6. If FAIL: address each Q1-Q13 failure
 * 7. Run: npm run verify-policy -- ${slug}
 * 8. If PASS: human review then push
 */

`;

  const code =
    banner +
    'export const ' +
    varName +
    'Policy = ' +
    JSON.stringify(policy, null, 2).replace(/"__([^"]+)__"/g, '"$1"') +
    ' as const;\n\nexport const ' +
    varName +
    'Spokes = [];\n';

  return code;
}

async function main() {
  const slug = process.argv[2];
  if (!slug) {
    console.error('Usage: npx tsx scripts/extract-policy.ts <slug>');
    process.exit(1);
  }

  const rawPath = path.join(RAW_DIR, slug + '.json');
  if (!fs.existsSync(rawPath)) {
    console.error('Raw collection not found: ' + rawPath);
    console.error('Run: npx tsx scripts/collect-multi-source.ts <keyword> <slug>');
    process.exit(1);
  }

  const raw: RawCollection = JSON.parse(fs.readFileSync(rawPath, 'utf-8'));
  const code = emitPolicy(raw);

  if (!fs.existsSync(POLICIES_DIR)) fs.mkdirSync(POLICIES_DIR, { recursive: true });
  const outPath = path.join(POLICIES_DIR, slug + '.ts');
  fs.writeFileSync(outPath, code, 'utf-8');

  console.log('Policy skeleton written: ' + outPath);
  console.log('');
  console.log('NEXT: open the file and replace all __FILL_*__ placeholders');
  console.log('      with verbatim quotes from data/raw/' + slug + '.json.');
  console.log('      Then run: npm run verify -- ' + slug);
}

main().catch((e) => { console.error(e); process.exit(1); });
