import { chromium } from 'playwright';
const b = await chromium.launch();
const p = await b.newPage();
await p.goto('https://www.google.com/search?q=' + encodeURIComponent(process.argv[2]), { waitUntil: 'domcontentloaded', timeout: 30000 });
await p.waitForTimeout(2000);
const html = await p.content();
const urls = [...new Set([...html.matchAll(/href="\/url\?q=(https?:\/\/[^"&]+)/g)].map(m => decodeURIComponent(m[1])))];
const plain = [...new Set([...html.matchAll(/<a[^>]+href="(https?:\/\/(?!www\.google|policies\.google|support\.google|accounts\.google|maps\.google)[^"]+)"/g)].map(m => m[1]))];
console.log([...urls, ...plain].slice(0, 10).join('\n'));
await b.close();
